NIST_800_82_CONTROLS = {
    "Access Control (AC)": {
        "AC-1": "Access Control Policy and Procedures",
        "AC-2": "Account Management",
        "AC-3": "Access Enforcement",
        "AC-4": "Information Flow Enforcement",
        "AC-5": "Separation of Duties",
        "AC-6": "Least Privilege",
        "AC-7": "Unsuccessful Logon Attempts",
        "AC-8": "System Use Notification",
        "AC-9": "Previous Logon (Access) Notification",
        "AC-10": "Concurrent Session Control",
        "AC-11": "Session Lock",
        "AC-12": "Session Termination",
        "AC-14": "Permitted Actions Without Identification or Authentication",
        "AC-17": "Remote Access",
        "AC-18": "Wireless Access",
        "AC-20": "Use of External Information Systems",
        "AC-21": "Information Sharing",
        "AC-22": "Publicly Accessible Content",
        "AC-24": "Access Control Decisions",
    },
    "Awareness and Training (AT)": {
        "AT-1": "Security Awareness and Training Policy and Procedures",
        "AT-2": "Security Awareness Training",
        "AT-3": "Role-Based Security Training",
        "AT-4": "Security Training Records",
    },
    "Audit and Accountability (AU)": {
        "AU-1": "Audit and Accountability Policy and Procedures",
        "AU-2": "Audit Events",
        "AU-3": "Content of Audit Records",
        "AU-4": "Audit Storage Capacity",
        "AU-5": "Response to Audit Processing Failures",
        "AU-6": "Audit Review, Analysis, and Reporting",
        "AU-7": "Audit Reduction and Report Generation",
        "AU-8": "Time Stamps",
        "AU-9": "Protection of Audit Information",
        "AU-10": "Non-Repudiation",
        "AU-11": "Audit Record Retention",
        "AU-12": "Audit Generation",
    },
    "Security Assessment and Authorization (CA)": {
        "CA-1": "Security Assessment and Authorization Policy and Procedures",
        "CA-2": "Security Assessments",
        "CA-3": "System Interconnections",
        "CA-5": "Plan of Action and Milestones",
        "CA-6": "Security Authorization",
        "CA-7": "Continuous Monitoring",
        "CA-8": "Penetration Testing",
        "CA-9": "Internal System Connections",
    },
    "Configuration Management (CM)": {
        "CM-1": "Configuration Management Policy and Procedures",
        "CM-2": "Baseline Configuration",
        "CM-3": "Configuration Change Control",
        "CM-4": "Security Impact Analysis",
        "CM-5": "Access Restrictions for Change",
        "CM-6": "Configuration Settings",
        "CM-7": "Least Functionality",
        "CM-8": "Information System Component Inventory",
        "CM-9": "Configuration Management Plan",
        "CM-10": "Software Usage Restrictions",
        "CM-11": "User-Installed Software",
    },
    "Contingency Planning (CP)": {
        "CP-1": "Contingency Planning Policy and Procedures",
        "CP-2": "Contingency Plan",
        "CP-3": "Contingency Training",
        "CP-4": "Contingency Plan Testing",
        "CP-6": "Alternate Storage Site",
        "CP-7": "Alternate Processing Site",
        "CP-8": "Telecommunications Services",
        "CP-9": "Information System Backup",
        "CP-10": "Information System Recovery and Reconstitution",
    },
    "Identification and Authentication (IA)": {
        "IA-1": "Identification and Authentication Policy and Procedures",
        "IA-2": "Identification and Authentication (Organizational Users)",
        "IA-3": "Device Identification and Authentication",
        "IA-4": "Identifier Management",
        "IA-5": "Authenticator Management",
        "IA-6": "Authenticator Feedback",
        "IA-7": "Cryptographic Module Authentication",
        "IA-8": "Identification and Authentication (Non-Organizational Users)",
    },
    "Incident Response (IR)": {
        "IR-1": "Incident Response Policy and Procedures",
        "IR-2": "Incident Response Training",
        "IR-3": "Incident Response Testing",
        "IR-4": "Incident Handling",
        "IR-5": "Incident Monitoring",
        "IR-6": "Incident Reporting",
        "IR-7": "Incident Response Assistance",
        "IR-8": "Incident Response Plan",
    },
    "Maintenance (MA)": {
        "MA-1": "System Maintenance Policy and Procedures",
        "MA-2": "Controlled Maintenance",
        "MA-3": "Maintenance Tools",
        "MA-4": "Nonlocal Maintenance",
        "MA-5": "Maintenance Personnel",
        "MA-6": "Timely Maintenance",
    },
    "Media Protection (MP)": {
        "MP-1": "Media Protection Policy and Procedures",
        "MP-2": "Media Access",
        "MP-3": "Media Marking",
        "MP-4": "Media Storage",
        "MP-5": "Media Transport",
        "MP-6": "Media Sanitization",
        "MP-7": "Media Use",
    },
    "Physical and Environmental Protection (PE)": {
        "PE-1": "Physical and Environmental Protection Policy and Procedures",
        "PE-2": "Physical Access Authorizations",
        "PE-3": "Physical Access Control",
        "PE-4": "Access Control for Transmission Medium",
        "PE-5": "Access Control for Output Devices",
        "PE-6": "Monitoring Physical Access",
        "PE-8": "Visitor Access Records",
        "PE-9": "Power Equipment and Cabling",
        "PE-10": "Emergency Shutoff",
        "PE-11": "Emergency Power",
        "PE-12": "Emergency Lighting",
        "PE-13": "Fire Protection",
        "PE-14": "Temperature and Humidity Controls",
        "PE-15": "Water Damage Protection",
        "PE-16": "Delivery and Removal",
    },
    "Planning (PL)": {
        "PL-1": "Security Planning Policy and Procedures",
        "PL-2": "System Security Plan",
        "PL-4": "Rules of Behavior",
        "PL-8": "Information Security Architecture",
    },
    "Program Management (PM)": {
        "PM-1": "Information Security Program Plan",
        "PM-2": "Senior Information Security Officer",
        "PM-3": "Information Security Resources",
        "PM-4": "Plan of Action and Milestones Process",
        "PM-5": "Information System Inventory",
        "PM-6": "Information Security Measures of Performance",
        "PM-7": "Enterprise Architecture",
        "PM-8": "Critical Infrastructure Plan",
        "PM-9": "Risk Management Strategy",
        "PM-10": "Security Authorization Process",
        "PM-11": "Mission/Business Process Definition",
        "PM-12": "Insider Threat Program",
        "PM-13": "Security and Privacy Workforce",
        "PM-14": "Testing, Training, and Monitoring",
        "PM-15": "Contacts with Groups",
        "PM-16": "Threat Awareness Program",
    },
    "Personnel Security (PS)": {
        "PS-1": "Personnel Security Policy and Procedures",
        "PS-2": "Position Risk Designation",
        "PS-3": "Personnel Screening",
        "PS-4": "Personnel Termination",
        "PS-5": "Personnel Transfer",
        "PS-6": "Access Agreements",
        "PS-7": "Third-Party Personnel Security",
        "PS-8": "Personnel Sanctions",
    },
    "Risk Assessment (RA)": {
        "RA-1": "Risk Assessment Policy and Procedures",
        "RA-2": "Security Categorization",
        "RA-3": "Risk Assessment",
        "RA-5": "Vulnerability Scanning",
        "RA-6": "Technical Surveillance Countermeasures Survey",
    },
    "System and Services Acquisition (SA)": {
        "SA-1": "System and Services Acquisition Policy and Procedures",
        "SA-2": "Allocation of Resources",
        "SA-3": "System Development Life Cycle",
        "SA-4": "Acquisition Process",
        "SA-5": "Information System Documentation",
        "SA-8": "Security Engineering Principles",
        "SA-9": "External Information System Services",
        "SA-10": "Developer Configuration Management",
        "SA-11": "Developer Security Testing and Evaluation",
        "SA-15": "Development Process, Standards, and Tools",
        "SA-17": "Developer Security Architecture and Design",
    },
    "System and Communications Protection (SC)": {
        "SC-1": "System and Communications Protection Policy and Procedures",
        "SC-2": "Application Partitioning",
        "SC-3": "Security Function Isolation",
        "SC-4": "Information in Shared Resources",
        "SC-5": "Denial of Service Protection",
        "SC-6": "Resource Availability",
        "SC-7": "Boundary Protection",
        "SC-8": "Transmission Confidentiality and Integrity",
        "SC-10": "Network Disconnect",
        "SC-11": "Trusted Path",
        "SC-12": "Cryptographic Key Establishment and Management",
        "SC-13": "Cryptographic Protection",
        "SC-15": "Collaborative Computing Devices",
        "SC-17": "Public Key Infrastructure Certificates",
        "SC-18": "Mobile Code",
        "SC-19": "Voice Over Internet Protocol",
        "SC-20": "Secure Name/Address Resolution Service",
        "SC-21": "Secure Name/Address Resolution Service (Recursive or Caching)",
        "SC-22": "Architecture and Provisioning for Name/Address Resolution Service",
        "SC-23": "Session Authenticity",
        "SC-24": "Fail in Known State",
        "SC-28": "Protection of Information at Rest",
        "SC-39": "Process Isolation",
    },
    "System and Information Integrity (SI)": {
        "SI-1": "System and Information Integrity Policy and Procedures",
        "SI-2": "Flaw Remediation",
        "SI-3": "Malicious Code Protection",
        "SI-4": "Information System Monitoring",
        "SI-5": "Security Alerts, Advisories, and Directives",
        "SI-6": "Security Function Verification",
        "SI-7": "Software, Firmware, and Information Integrity",
        "SI-8": "Spam Protection",
        "SI-10": "Information Input Validation",
        "SI-11": "Error Handling",
        "SI-12": "Information Handling and Retention",
        "SI-13": "Predictable Failure Prevention",
        "SI-14": "Non-Persistence",
        "SI-15": "Information Output Filtering",
        "SI-16": "Memory Protection",
    },
}

CODE_VERIFIABLE_CONTROLS = {
    "AC-3": "Access Enforcement - Verificable en código de autorización (roles, JWT, OAuth)",
    "AC-6": "Least Privilege - Verificable en asignación de roles y permisos",
    "AC-17": "Remote Access - Verificable en configuración de acceso remoto",
    "AU-2": "Audit Events - Verificable en configuración de logging",
    "AU-3": "Content of Audit Records - Verificable en formato de logs",
    "AU-12": "Audit Generation - Verificable en código de auditoría",
    "CM-6": "Configuration Settings - Verificable en archivos de configuración",
    "CM-7": "Least Functionality - Verificable en Dockerfile y configuraciones",
    "IA-2": "Identification and Authentication - Verificable en auth module",
    "IA-5": "Authenticator Management - Verificable en password policies, MFA",
    "IA-7": "Cryptographic Module Authentication - Verificable en crypto usage",
    "RA-5": "Vulnerability Scanning - Verificable en workers de escaneo",
    "SA-10": "Developer Configuration Management - Verificable en CI/CD",
    "SA-11": "Developer Security Testing - Verificable en tests de seguridad",
    "SC-7": "Boundary Protection - Verificable en CORS, rate limiting",
    "SC-8": "Transmission Confidentiality - Verificable en HTTPS/TLS config",
    "SC-13": "Cryptographic Protection - Verificable en uso de criptografía",
    "SC-23": "Session Authenticity - Verificable en JWT config",
    "SC-28": "Protection of Information at Rest - Verificable en encryption config",
    "SI-2": "Flaw Remediation - Verificable en dependency updates",
    "SI-10": "Information Input Validation - Verificable en validaciones de entrada",
    "SI-11": "Error Handling - Verificable en manejo de errores",
}


class NIST80082Rules:
    def evaluate(self, knowledge_base: dict) -> dict:
        result = {}
        for family, controls in NIST_800_82_CONTROLS.items():
            result[family] = {}
            for ctrl_id, ctrl_name in controls.items():
                is_verifiable = ctrl_id in CODE_VERIFIABLE_CONTROLS
                result[family][ctrl_id] = {
                    "nombre": ctrl_name,
                    "verificable_por_codigo": is_verifiable,
                    "estado": "verificable" if is_verifiable else "requiere_evidencia_externa",
                    "nota": CODE_VERIFIABLE_CONTROLS.get(ctrl_id, "NO ES POSIBLE VALIDAR CON EL CÓDIGO - Requiere evidencia externa"),
                }

        total = sum(len(controls) for controls in NIST_800_82_CONTROLS.values())
        verified = sum(
            1 for family in result.values() for ctrl in family.values() if ctrl["verificable_por_codigo"]
        )

        return {
            "standard": "NIST SP 800-82 Rev.3",
            "total_controls": total,
            "controls_verified_by_code": verified,
            "score": (verified / total) * 100 if total > 0 else 0,
            "controls": result,
            "non_verifiable_controls": total - verified,
        }
